const Product = require('../models/Product');

/**
 * GET /api/products
 * List active products with optional filtering, search, and pagination.
 *
 * Query params:
 *   category  — exact match on product category
 *   search    — case-insensitive regex on name OR description
 *   page      — page number (default: 1)
 *   limit     — items per page (default: 20, max: 100)
 */
async function listProducts(req, res, next) {
  try {
    const { category, search } = req.query;

    // Parse and clamp pagination params
    const page = Math.max(1, parseInt(req.query.page, 10) || 1);
    const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));
    const skip = (page - 1) * limit;

    // Build filter — always restrict to active products
    const filter = { isActive: true };

    if (category) {
      filter.category = category;
    }

    if (search) {
      const regex = new RegExp(search, 'i');
      filter.$or = [{ name: regex }, { description: regex }];
    }

    const [products, total] = await Promise.all([
      Product.find(filter)
        .select('name slug category images basePrice averageRating reviewCount stock variants isActive')
        .lean()
        .skip(skip)
        .limit(limit)
        .sort({ createdAt: -1 }),
      Product.countDocuments(filter),
    ]);

    const totalPages = Math.ceil(total / limit);

    return res.json({
      success: true,
      data: {
        products,
        total,
        page,
        totalPages,
      },
    });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/products/:slug
 * Return full product detail for a single active product by slug.
 * Computes inStock at product level and per variant.
 */
async function getProduct(req, res, next) {
  try {
    const { slug } = req.params;

    const product = await Product.findOne({ slug, isActive: true }).lean();

    if (!product) {
      return res.status(404).json({
        success: false,
        error: { code: 'NOT_FOUND', message: 'Product not found' },
      });
    }

    // Compute inStock per variant
    if (product.variants && product.variants.length > 0) {
      product.variants = product.variants.map((v) => ({
        ...v,
        inStock: v.stock > 0,
      }));
    }

    // Compute inStock at product level: product.stock > 0 OR any variant has stock > 0
    const variantInStock =
      product.variants && product.variants.some((v) => v.stock > 0);
    product.inStock = product.stock > 0 || variantInStock;

    return res.json({ success: true, data: { product } });
  } catch (err) {
    next(err);
  }
}

/**
 * POST /api/products
 * Admin: create a new product.
 * Required fields: name, category, description, basePrice, stock, images (array >= 1)
 */
async function createProduct(req, res, next) {
  try {
    const { name, category, description, basePrice, stock, images, ...rest } = req.body;

    // Validate required fields
    const missing = [];
    if (!name) missing.push('name');
    if (!category) missing.push('category');
    if (!description) missing.push('description');
    if (basePrice === undefined || basePrice === null) missing.push('basePrice');
    if (stock === undefined || stock === null) missing.push('stock');
    if (!images) missing.push('images');

    if (missing.length > 0) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'VALIDATION_ERROR',
          message: 'Missing required fields',
          details: missing,
        },
      });
    }

    if (typeof basePrice !== 'number' || basePrice <= 0) {
      return res.status(400).json({
        success: false,
        error: { code: 'VALIDATION_ERROR', message: 'basePrice must be a number greater than 0', details: [] },
      });
    }

    if (typeof stock !== 'number' || stock < 0) {
      return res.status(400).json({
        success: false,
        error: { code: 'VALIDATION_ERROR', message: 'stock must be a number >= 0', details: [] },
      });
    }

    if (!Array.isArray(images) || images.length < 1) {
      return res.status(400).json({
        success: false,
        error: { code: 'VALIDATION_ERROR', message: 'images must be an array with at least 1 item', details: [] },
      });
    }

    const product = new Product({ name, category, description, basePrice, stock, images, ...rest });
    await product.save();

    return res.status(201).json({ success: true, data: { product } });
  } catch (err) {
    next(err);
  }
}

/**
 * PUT /api/products/:id
 * Admin: update an existing product (partial update).
 * Slug is regenerated by pre-save hook if name changes.
 */
async function updateProduct(req, res, next) {
  try {
    const { id } = req.params;

    const product = await Product.findById(id);
    if (!product) {
      return res.status(404).json({
        success: false,
        error: { code: 'NOT_FOUND', message: 'Product not found' },
      });
    }

    // Apply only the fields present in req.body
    const allowedFields = ['name', 'category', 'description', 'basePrice', 'stock', 'images',
      'ingredients', 'variants', 'isActive', 'lowStockThreshold', 'tags'];

    for (const field of allowedFields) {
      if (req.body[field] !== undefined) {
        product[field] = req.body[field];
      }
    }

    await product.save();

    return res.json({ success: true, data: { product } });
  } catch (err) {
    next(err);
  }
}

/**
 * DELETE /api/products/:id
 * Admin: soft-delete a product by setting isActive: false.
 */
async function deleteProduct(req, res, next) {
  try {
    const { id } = req.params;

    const product = await Product.findById(id);
    if (!product) {
      return res.status(404).json({
        success: false,
        error: { code: 'NOT_FOUND', message: 'Product not found' },
      });
    }

    product.isActive = false;
    await product.save();

    return res.json({ success: true, message: 'Product deleted' });
  } catch (err) {
    next(err);
  }
}

module.exports = { listProducts, getProduct, createProduct, updateProduct, deleteProduct };
